### ISSUE TITLE
format for vocabulary file

### ISSUE THREAD

**Issue by ducanh841988** [jermp/tongrams#14]
Thank you for your amazing work @jermp.
I am trying to sort an arpa file as the following command
 ./sort_arpa 3 input.arpa vocab.txt output.arpa
It cased the following error:

Building vocabulary    
terminate called after throwing an instance of 'std::runtime_error'    
  what():  first line must be non-empty and contain the number of lines.    
Aborted (core dumped)

I think the problem is my vocab.txt does not in the correct format. Could you give me an example for vocab file?

Thank you in advance.

>

**Comment by jermp** [comment]
Hi there,
try to add a line at the beginning of the vocab file with the number of lines
and compress it with gzip, like:
`gzip vocab.txt`
which should produce a gzipped file `vocab.txt.gz`.

To see another example, using the test files contained in the `test_data` directory of the project, run the following:
`./sort_arpa 5 ../test_data/arpa ../test_data/1-grams.sorted.gz arpa.sorted --tmp ./tmp`.

Let me know if I can assist you further.
