### ISSUE TITLE
an error when I try  python tongrams

### ISSUE THREAD

**Issue by ducanh841988** [jermp/tongrams#15]
Hi Giulio Ermanno Pibiri,

I installed python wrapper, but when I import tongrams, I faced this error:

 import tongrams
ImportError: /opt/conda/lib/python3.7/site-packages/tongrams.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8tongrams12trie_prob_lmINS_18double_valued_mphtIN5emphf16jenkins64_hasherEEENS_15identity_mapperENS_29quantized_sequence_collectionENS_14compact_vectorENS_16fast_ef_sequenceENS_11ef_sequenceEE5scoreERNS_16prob_model_stateImEESt4pairIPKhSG_ERb

could you help me to solve this error?
Thank in advance

**Comment by jermp** [comment]
Hi,
yes now I'am facing this error too. Strange, it worked perfectly before.
Anyway, I have added a missing include to the `python/tongrams.cpp` module:

`#include "score.hpp"`

Now reinstall the py wrapper and try the example. On my end it works (tried both Mac 10.15 and Linux 5).
Let me know.

**Comment by ducanh841988** [comment]
Thank you. It works perfectly.
