### ISSUE TITLE
how to use tongram in a class

### ISSUE THREAD

**Issue by ducanh841988** [jermp/tongrams#16]
Hi @jermp 

I want to add n-gram model to a class, but I don't know how to call the class from the main function.

I defined class A which contain n-gram model

template <typename Model>
class A
{
private:
    Model* model;
    
public:
    A(string model_path = ""){
          model = new Model;
          tongrams::util::load(*(model), model_path);
     }
    void fool(){
            auto state = model->state();
     }
};

but in main(), I don't know how to call class A, since I need a specific type for the model. 
Do you know how to solve this?

Thank you in advance.

**Comment by jermp** [comment]
Hi, this is not an "issue" related to Tongrams, rather to C++ programming.
In fact, I do not understand your code.
I see that you want a class that has a template parameter to specify the n-gram model type.
So it should look like this:

    template <typename Model>
    struct A {

    /* all your public methods */

    private:
        Model model;
    };

and then, in the main, you should specify the type of the model using one among those in the header file `lm_types.hpp`.
For example:

     A<ef_trie_IC_ranks_count_lm> my_obj;
