### ISSUE TITLE
Can't load MPH-based models in Python

### ISSUE THREAD

**Issue by abdullah-saal** [jermp/tongrams#22]
Created MPH-based model with 
```
./build_hash  3 8 count --dir ./trie_data/ --out hash.bin
```
It works with the given executables, `test_count_model` and `print_stats`,
but when I try to load it in Python I get the following error:
```
==== tongrams binary format ====
library version: 1.0
data structure type: mph
hash_key_bytes: 8
value type: count
================================
Loading data structure type: mph64_count_lm
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Python Code:
```python
import tongrams

count_model_filename = "./hash.bin"
count_model = tongrams.CountModel(count_model_filename)
```

**Comment by jermp** [comment]
Only trie-based models are currently supported by the Python wrapper.
So you built a hash data structure and you are trying to parse it as a trie.
The error you are getting is expected.
