### ISSUE TITLE
sort_grams - found the bug causing the exception

### ISSUE THREAD

**Issue by ndvbd** [jermp/tongrams#3]
Apparently, sort_grams fails when the 3rd argument is a full path of file.
So doing 

`./sort_grams 1-grams.sorted.gz 1-grams.sorted.gz 1-grams.sorted.again.txt`

Works, but

`./sort_grams 1-grams.sorted.gz 1-grams.sorted.gz /usr/tongrams/1-grams.sorted.done.txt`

Fails with

```
terminate called without an active exception
Aborted (core dumped)
```

**Comment by jermp** [comment]
Well, it is not a bug.
Because probably you do not have permissions to write to the file
/usr/tongrams/1-grams.sorted.done.txt

**Comment by ndvbd** [comment]
I have permissions. 
It's on every directory. If I run the executable from within the directory it works, if I give the exact file with full path it doesn't

**Comment by jermp** [comment]
Ok, fixed.

**Comment by ndvbd** [comment]
@jermp thanks!
